spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cash_register?characterEncoding=utf-8&amp;serverTimezone=UTC&amp;useSSL=false
    username: root
    password: 123

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

server:
  port: 8090


mybatis:
  mapper-locations: classpath*:mapper/*.xml
